### ISSUE TITLE
Multiple Projects in One

### ISSUE THREAD

**Issue by pnewell** [jgillick/jira-changelog#7]
Our product is split into a few separate projects (repositories), is it possible to combine a few into one? I tried placing the changelog.config.js in the top level directory but that didn't work. I don't mind running it multiple times, but would be nice if it could all be combined (and deduped) across projects (repositories).

**Comment by jgillick** [comment]
That's an interesting idea. The challenge is that it would still need to run commands like `git log` in each repo. Automating that could be a challenge and open up other potential issues. Perhaps a configuration could be added to run another script instead of `git log`. Then you'd just create a script that would get the log from all your repos and put them into a single list.

If you're interested at taking a stab at implementing this, I'd be happy to review the pull request.

**Comment by jgillick** [comment]
Actually, the easiest option is to create a master `changelog.config.js` and import it into your projects.

For example:
```
/<root directory>
  - changelog.master.js
  /project-1
      - changelog.config.js
  /project-2
      - changelog.config.js
```

The `changelog.config.js` file for each project would just look like this:

```js
const config = require('../changelog.master.js');
module.exports = config;
```

Let me know if that solves it. You'll still need to run the changelog script from each directory, but they can all use the same exact config.
